name: Format and Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  formatLint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: lts/*

      - name: Install Prettier with plugins
        run: |
          npm i -D prettier@latest

      - name: Format JSON and Markdown
        run: |
          npx prettier -w **/*.{md,json}

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: Install Flake8 and Black
        run: |
          pip install flake8 black

      - name: format python
        run: |
          black .

      - name: lint python
        run: |
          flake8 . --config .flake8

      - name: Clean up unnecessary files
        run: |
          rm -rf node_modules
          rm -f .prettierignore
          rm -f package.json
          rm -f package-lock.json

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: 'chore(ci): auto format + lint fixes'
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
